version: '3.8'

services:
    db:
        image: neo4j:2025.05.0
        container_name: neo4j-db
        env_file:
            - apps/graph-api/.db.env
        ports:
            - '7474:7474'
            - '7687:7687'
        volumes:
            - ./apps/graph-api/data:/data

    api:
        build:
            context: .
            dockerfile: apps/graph-api/Dockerfile
        container_name: graph-api
        env_file:
            - apps/graph-api/.env
        environment:
            - NODE_ENV=development
            - NEO4J_DB_URL=bolt://db:7687
        ports:
            - '4000:4000'
        depends_on:
            - db
