name: CI/CD

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    release:
        runs-on: ubuntu-latest
        outputs:
            src_changed: ${{ steps.filter.outputs.src }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: dorny/paths-filter@v3
              id: filter
              with:
                  filters: |
                      src:
                        - './packages/ui/**'
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: yarn install --frozen-lockfile --non-interactive
            - run: yarn workspaces run semantic-release -e semantic-release-monorepo
        env:
            GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

    deploy:
        needs: release
        if: needs.release.outputs.src_changed == 'true'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: yarn install --frozen-lockfile --non-interactive
            - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
              with:
                  install_command: yarn install
                  build_command: yarn build-storybook
