name: CI/CD

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            src_changed: ${{ steps.filter.outputs.src }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: dorny/paths-filter@v3
              id: filter
              with:
                  filters: |
                      src:
                        - './packages/ui/**'
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: yarn install --frozen-lockfile --non-interactive
              working-directory: .
            - uses: actions/upload-artifact@v4
              with:
                  name: build-artifact
                  path: .

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: build-artifact
                  path: .
            - run: yarn workspaces run semantic-release -e semantic-release-monorepo
              working-directory: .
        env:
            GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

    deploy:
        needs: build
        if: needs.build.outputs.src_changed == 'true'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: build-artifact
                  path: .
            - run: yarn install --frozen-lockfile --non-interactive
              working-directory: .
            - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
              with:
                  install_command: yarn install
                  build_command: yarn build-storybook
