name: Build and Publish Storybook to GitHub Pages

on:
    workflow_dispatch:
    push:
        branches:
            - 'main'

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: yarn install --frozen-lockfile --non-interactive
              working-directory: .
            - run: yarn build
              working-directory: .
            - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
              with:
                  install_command: yarn install
                  build_command: yarn build-storybook
                  path: './packages/ui/storybook-static'
                  checkout: false
